language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=1.25.1; TYPE=coverage
      php: 5.6
    - env: DB=mysql; MW=1.23.9;
      php: 5.4
    - env: DB=sqlite; MW=1.24.1; SITELANG=ja
      php: 5.5
    - env: DB=sqlite; MW=master; PHPUNIT=4.7.*
      php: '7'
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
     - env: DB=sqlite; MW=master; PHPUNIT=4.7.*

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-meta-tags.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: change
    on_failure: always
